name: kai_tw_ui_kit
description: This is a UI kit that shares Flutter components through my projects.
version: 1.0.0
repository: https://github.com/kai-tw/flutter_ui_kit

environment:
  sdk: ">=3.2.3 <4.0.0"

# Add regular dependencies here.
dependencies:
  # path: ^1.9.0
  flutter:
    sdk: flutter
  flutter_lints: ^6.0.0
  package_info_plus: ^9.0.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
