name: flutter_ui_kit
description: A starting point for Dart libraries or applications.
version: 1.0.0
#repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  # path: ^1.9.0
  flutter:
    sdk: flutter
  flutter_lints: ^6.0.0
  package_info_plus: ^9.0.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
